---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Root
  create: all
  match: "**/*"
upload_dir: public
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:-:year:-:month:-:day:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
